package_mappings:
  - paper-datatable: custom_elements
  - paper-calendar: custom_elements
  - paper-date: custom_elements
  - paper-clock: custom_elements
  - paper-time: custom_elements
  - paper-year: custom_elements
  - iron-: polymer_elements
  - neon-: polymer_elements
  - paper-: polymer_elements
  - shadow: polymer_elements
  - typography: polymer_elements
  # For mixin classes
  - Iron: polymer_elements
  - Paper: polymer_elements
# Configuration for running tool/generate_dart_api.dart
files_to_generate:
  - moment-element/moment-import.html
  - moment-element/moment-with-locales-import.html
  - vaadin-date-picker/vaadin-date-picker-behavior.html:
     omit_imports:
       - iron-form-element-behavior
       - iron-validatable-behavior
       - iron-a11y-keys-behavior
     extra_imports:
       - package:polymer_elements/iron_form_element_behavior.dart
       - package:polymer_elements/iron_validatable_behavior.dart
       - package:polymer_elements/iron_a11y_keys_behavior.dart
  - vaadin-date-picker/vaadin-date-picker-helper.html
  - vaadin-date-picker/vaadin-date-picker.html:
     omit_imports:
       - iron-form-element-behavior
       - iron-validatable-behavior
       - iron-a11y-keys-behavior
     extra_imports:
       - package:polymer_elements/iron_form_element_behavior.dart
       - package:polymer_elements/iron_validatable_behavior.dart
       - package:polymer_elements/iron_a11y_keys_behavior.dart

  - vaadin-date-picker/vaadin-date-picker-icons.html
  - vaadin-date-picker/vaadin-date-picker-light.html:
     omit_imports:
       - iron-form-element-behavior
       - iron-validatable-behavior
       - iron-a11y-keys-behavior
     extra_imports:
       - package:polymer_elements/iron_form_element_behavior.dart
       - package:polymer_elements/iron_validatable_behavior.dart
       - package:polymer_elements/iron_a11y_keys_behavior.dart
  - vaadin-date-picker/vaadin-date-picker-overlay.html
  - vaadin-date-picker/vaadin-infinite-scroller.html:
      omit_imports:
         - templatizer.html
  - vaadin-date-picker/vaadin-month-calendar.html
  - vaadin-split-layout/vaadin-split-layout.html:
     omit_imports:
      - src/iron-resizable-behavior
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
  - vaadin-icons/vaadin-icons.html
  - vaadin-grid/vaadin-grid.html:
     overrides:
      VaadinGrid:
       cellClassGenerator:
        -  "/// A function which is used for generating CSS class names for data cells."
        -  "get cellClassGenerator => jsElement[r'cellClassGenerator'];"
        -  "set cellClassGenerator(value) { jsElement[r'cellClassGenerator'] = (value is Map || (value is Iterable && value is! JsArray)) ? new JsObject.jsify(value) : value;}"
       rowClassGenerator:
        - "/// A function which is used for generating CSS class names for data rows."
        - "get rowClassGenerator => jsElement[r'rowClassGenerator'];"
        - "set rowClassGenerator(value) { jsElement[r'rowClassGenerator'] = (value is Map || (value is Iterable && value is! JsArray)) ? new JsObject.jsify(value) : value;}"
       rowDetailsGenerator:
        - "///  The row details generator is used for generating detail content for"
        - "/// data rows. The details element is added directly under the row."
        - "get rowDetailsGenerator => jsElement[r'rowDetailsGenerator'];"
        - "set rowDetailsGenerator(value) { jsElement[r'rowDetailsGenerator'] = (value is Map || (value is Iterable && value is! JsArray)) ? new JsObject.jsify(value) : value;}"
  - paper-divider/paper-divider.html
  - paper-time-picker/paper-time-picker.html:
     omit_imports:
      - src/iron-resizable-behavior
      - fade-in-animation.html
      - fade-out-animation.html
      - classlist-shim.html
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
      - package:polymer_elements/neon_animation/animations/fade_in_animation.dart
      - package:polymer_elements/neon_animation/animations/fade_out_animation.dart
  - paper-time-picker/paper-clock-selector.html:
      omit_imports:
       - src/iron-resizable-behavior
       - classlist-shim.html
      extra_imports:
       - package:polymer_elements/iron_resizable_behavior.dart
  - paper-time-picker/paper-time-picker-dialog-style.html
  - paper-chip/paper-chip.html:
     omit_imports:
      - iron-behaviors
      - iron-a11y-keys-behavior.html
     extra_imports:
      - package:polymer_elements/iron_button_state.dart
      - package:polymer_elements/iron_a11y_keys_behavior.dart
      - package:polymer_elements/iron_control_state.dart
  - moment-element/moment-with-locales-import.html
  - polymer-paper-date-picker/paper-year-list.html:
     omit_imports:
      - default-theme.html
      - src/iron-resizable-behavior
      - fade-in-animation.html
      - fade-out-animation.html
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
      - package:polymer_elements/default_theme.dart
      - package:polymer_elements/neon_animation/animations/fade_in_animation.dart
      - package:polymer_elements/neon_animation/animations/fade_out_animation.dart
  - polymer-paper-date-picker/paper-date-picker-icons.html
  - polymer-paper-date-picker/paper-date-picker.html:
     omit_imports:
      - src/iron-resizable-behavior
      - default-theme.html
      - shadow.html
      - color.html
      - fade-in-animation.html
      - fade-out-animation.html
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
      - package:polymer_elements/neon_animation/animations/fade_in_animation.dart
      - package:polymer_elements/neon_animation/animations/fade_out_animation.dart
  - polymer-paper-date-picker/paper-calendar.html:
      omit_imports:
       - src/iron-resizable-behavior
       - default-theme.html
       - shadow.html
       - color.html
      extra_imports:
       - package:polymer_elements/iron_resizable_behavior.dart
  - polymer-paper-date-picker/paper-date-picker-dialog-style.html

  - paper-datatable/paper-datatable.html:
     omit_imports:
      - src/iron-resizable-behavior
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
  - paper-datatable/paper-datatable-column.html:
      omit_imports:
         - templatizer.html
      name_substitutions:
        default: defaultValue
  - paper-datatable/paper-datatable-edit-dialog.html:
     omit_imports:
      - src/iron-resizable-behavior
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart
  - paper-datatable/datatable-icons.html
  - iron-data-table/data-table-cell.html:
     omit_imports:
        - templatizer.html
        - templatizer-behavior.html
     extra_imports:
        - "data_table_templatizer_behavior.dart' as saulis; //"
  - iron-data-table/data-table-icons.html
  - iron-data-table/data-table-templatizer-behavior.html:
     omit_imports:
        - templatizer.html
  - iron-data-table/data-table-column-filter.html  
  - iron-data-table/data-table-column-sort.html  
  - iron-data-table/data-table-checkbox.html  
  - iron-data-table/data-table-column.html:
     omit_imports:
        - templatizer.html
  - iron-data-table/default-styles.html	      
  - iron-data-table/iron-data-table.html:
     omit_imports:
      - src/iron-resizable-behavior
     extra_imports:
      - package:polymer_elements/iron_resizable_behavior.dart

  - iron-data-table/data-table-row-detail.html:
     omit_imports:
        - templatizer.html
        - templatizer-behavior.html
     extra_imports:
        - "data_table_templatizer_behavior.dart' as saulis; //"
  - iron-data-table/data-table-row.html
#lib/src/iron-data-table/default-styles.html


  - vaadin-upload/vaadin-upload.html
  - vaadin-upload/vaadin-upload-file.html
  - vaadin-upload/vaadin-upload-icons.html
stubs_to_generate:
 polymer_elements:
  - iron-dropdown/iron-dropdown.html
  - iron-input/iron-input.html
#  - paper-input/paper-input-container.html
  - iron-a11y-announcer/iron-a11y-announcer.html
  - iron-overlay-behavior/iron-overlay-behavior.html
  - iron-meta/iron-meta.html
#  - paper-input/paper-input-error.html
  - paper-checkbox/paper-checkbox.html
  - paper-tooltip/paper-tooltip.html
  - iron-resizable-behavior/iron-resizable-behavior.html
  - iron-list/iron-list.html
  - paper-spinner/paper-spinner.html
  - paper-spinner/paper-spinner-behavior.html
  - paper-spinner/paper-spinner-lite.html
  - paper-spinner/paper-spinner-styles.html
  - paper-input/paper-input.html
  - iron-icon/iron-icon.html
  - iron-iconset-svg/iron-iconset-svg.html
  - iron-icons/iron-icons.html
  - paper-ripple/paper-ripple.html
  - paper-material/paper-material.html
  - paper-button/paper-button.html
  - paper-styles/typography.html
  - paper-styles/color.html
  - paper-styles/shadow.html
  - paper-styles/default-theme.html
  - paper-progress/paper-progress.html
#  - paper-dropdown-menu/paper-dropdown-menu.html
#  - paper-menu/paper-menu.html
  - paper-item/paper-item.html
  - paper-icon-button/paper-icon-button.html
#  - paper-progress/paper-progress.html
  - paper-styles/paper-styles.html
  - iron-form/iron-form.html
  - font-roboto/roboto.html
  - neon-animation/neon-animatable.html
  - neon-animation/animations/fade-in-animation.html
  - neon-animation/animations/fade-out-animation.html
  - iron-media-query/iron-media-query.html
  - neon-animation/neon-animated-pages.html
  - iron-selector/iron-selector.html
  - iron-flex-layout/iron-flex-layout.html
  - iron-a11y-keys/iron-a11y-keys.html
  - iron-behaviors/iron-button-state.html
  - iron-behaviors/iron-control-state.html
  - iron-form-element-behavior/iron-form-element-behavior.html
  - iron-validatable-behavior/iron-validatable-behavior.html
  - paper-toast/paper-toast.html
 polymer:
  - polymer/polymer.html
files_to_load:
  - package:polymer_interop/src/js/debug/src/lib/template/templatizer.html
  - package:polymer_elements/src/iron-resizable-behavior/iron-resizable-behavior.html
  - package:polymer_elements/src/iron-behaviors/iron-button-state.html
  - package:polymer_elements/src/iron-behaviors/iron-control-state.html
  - package:polymer_elements/src/iron-a11y-keys-behavior/iron-a11y-keys-behavior.html
  - package:polymer_elements/src/iron-form-element-behavior/iron-form-element-behavior.html
  - package:polymer_elements/src/iron-validatable-behavior/iron-validatable-behavior.html
#  - package:polymer_elements/src/iron-list/iron-list.html
#  - package:polymer_elements/src/paper-checkbox/paper-checkbox.html
#  - package:polymer_elements/src/paper-tooltip/paper-tooltip.html
deletion_patterns:
 - ^iron-ajax
 - ^font-roboto
 - ^iron-auto
 - ^iron-check
 - ^iron-flex
 - ^iron-form
 - ^iron-inp
 - ^iron-met
 - ^iron-scr
 - ^iron-val
 - ^promise
 - ^web
 - ^paper-behaviors
 - metadata\.html$
 - index\.html$
 - demo\.html$
 - demos$
 - demo$
 - README\.md$
 - .gitignore$
 - .travis.yml$
 - CONTRIBUTING\.md$
 - test
 - ^iron-icons/av-icons.html
 - ^iron-icons/communication-icons.html
 - ^iron-icons/device-icons.html
 - ^iron-icons/editor-icons.html
 - ^iron-icons/hardware-icons.html
 - ^iron-icons/hero.svg
 - ^iron-icons/image-icons.html
 - ^iron-icons/maps-icons.html
 - ^iron-icons/notification-icons.html
 - ^iron-icons/places-icons.html
 - ^iron-icons/social-icons.html
 - ^iron-iconset-svg
 - ^paper-input/paper-input-.*.html
 - ^paper-input/paper-textarea.html
 - ^paper-input/all-imports.html
 - ^polymer/polymer-*.html
 - ^prism
 - ^marked
 - ^iron-overlay
 - ^iron-range
 - ^paper-toast
 - ^iron-fit
 - ^iron-a11y-announcer
