name: custom_elements
version: 0.0.2
author: community <info@customelements.io>
description: Custom Elements from Community ported to dart
homepage: https://github.com/dart-lang/polymer_elements
dependencies:
  polymer_interop: ^1.0.0-rc.5
  web_components: ^0.12.0
  polymer_elements: ^1.0.0-rc.5
dev_dependencies:
  browser: ^0.10.0
  custom_element_apigen: ^0.2.1+1
  html5lib: ">=0.11.0 <0.13.0"
  path: ^1.0.0
  polymer: ^1.0.0-rc.6
  reflectable: ">=0.3.1 <0.5.0"
  test: ^0.12.5+1
  yaml: ">=1.0.0 <3.0.0"

dependency_overrides:
 custom_element_apigen:
  git: git@github.com:dam0vm3nt/custom-element-apigen.git
#  path: ../custom-element-apigen

#transformers:
#- web_components:
#    $include: test/*_test.html
#- reflectable:
#    $include: test/*_test.dart
#    entry_points:
#    - test/iron_a11y_keys_behavior_test.dart
#    - test/iron_behavior_active_state_test.dart
#    - test/iron_behavior_disabled_state_test.dart
#    - test/iron_behavior_focused_state_test.dart
#- test/pub_serve:
#    $include: test/**_test{.*,}.dart

environment:
  sdk: ">=1.8.0 <2.0.0"
