name: demo_custom_elements
description: Demo project for polymer datepicker
version: 0.0.2
author: Vittorio Ballestra <vittorio.ballestra@drafintech.it>
homepage: https://github.com/dam0vm3nt/polymer_autonotify
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  polymer: "^1.0.0-rc.15"
  polymer_elements: ^1.0.0-rc.7
  browser: any
  intl: any
  custom_elements:
    path: ..

dependency_overrides:
  polymer:
    hosted:
      name: polymer
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.19.unofficial.1"
  polymer_elements:
    hosted:
      name: polymer_elements
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.11+3"
  polymer_interop:
    hosted:
      name: polymer_interop
      url: "http://pub.drafintech.it:5001"
    version: "1.0.0-rc.10.exp.20161031.2"


#dependency_overrides:
# polymer_elements:
#  path: ../../polymer_elements
transformers:
- polymer:
    entry_points:
    - web/index.html
- $dart2js:
    $include: '**/*.bootstrap.initialize.dart'
    minify: false
    commandLineOptions:
    - --trust-type-annotations
    - --trust-primitives
